# This is a basic workflow to help you get started with Actions
name: GitHub Action - CTF to postman
on: 
  push:
    branches:
      - development_github
  repository_dispatch:
    types: [ctf-postman-webhook]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      CDA_ID:
        description: 'User CDA:'
        required: true
        default: "Hello World"
      CPA_ID:
        description: 'User CPA:'
        required: true
        default: "Hello World"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: >-
        github.event_name == 'repository_dispatch'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
        POSTMAN_FILE: postman/Contentful_cda_cpa_cma_gql_images_scim_postman.json
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo
        uses: actions/checkout@v4
       
      - name: Preparing
        run: mkdir tmp

      - name: Downloading Contentful CDA documentation
        run: |
           echo "Doing CDA ${{ github.event.inputs.CDA_ID }}"
              # curl -o ./tmp/cda.json https://www.contentful.com/developers/_resources/cda.${{ github.event.client_payload.CDA_ID }}.json

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
