name: GitHub Action - CTF to postman
on: 
  push:
    branches:
      - development_github
  repository_dispatch:
    types: [ctf-postman-webhook]
jobs:
  postman-webhook-stage:
      if: >-
        github.event_name == 'repository_dispatch'
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
        - run: echo "Script to create postman repo"
        - run: echo "Doing CDA ${{ github.event.client_payload.CDA_ID }}"
        - run: curl -o ./tmp/cda.json https://www.contentful.com/developers/_resources/cda.${{ github.event.client_payload.CDA_ID }}.json



