name: GitHub Action - CTF to postman
on: 
  push:
    branches:
      - development_github
  repository_dispatch:
    types: [ctf-postman-webhook]
jobs:
  postman-webhook-stage:
      if: >-
        github.event_name == 'repository_dispatch'
      runs-on: ubuntu-latest
      env:
        POSTMAN_FILE: postman/Contentful_cda_cpa_cma_gql_images_scim_postman.json
      steps:
        - name: checkout repo
          uses: actions/checkout@v3

        - name: Downloading Contentful CDA documentation
          run: |
              echo "Doing CDA ${{ github.event.client_payload.CDA_ID }}"
              curl -o cda.json https://www.contentful.com/developers/_resources/cda.${{ github.event.client_payload.CDA_ID }}.json

        - name: Downloading Contentful CPA documentation
          run: |
              echo "Doing CPA ${{ github.event.client_payload.CPA_ID }}"
              curl -o cpa.json https://www.contentful.com/developers/_resources/cpa.${{ github.event.client_payload.CPA_ID }}.json
              
        - name: Downloading Contentful CMA documentation
          run: |
              echo "Doing CMA ${{ github.event.client_payload.CMA_ID }}"  
              curl -o cma.json https://www.contentful.com/developers/_resources/cma.${{ github.event.client_payload.CMA_ID }}.json
                          
        - name: Downloading Contentful IMAGES API documentation
          run: |
              echo "Doing IMAGES ${{ github.event.client_payload.IMAGES_ID }}"
              curl -o images.json https://www.contentful.com/developers/_resources/images.${{ github.event.client_payload.IMAGES_ID }}.json
            
        - name: Downloading Contentful SCIM API documentation
          run: |
              echo "Doing SCIM ${{ github.event.client_payload.SCIM_ID }}"
              curl -o scim.json https://www.contentful.com/developers/_resources/scim.${{ github.event.client_payload.SCIM_ID }}.json
            
        - name: Transforming to Postman
          run: ./postman_convert -v ${{github.event.client_payload.API_VERSION}} > ${{ env.POSTMAN_FILE }}

        - name: Commit files
          run: |
              git config --global user.email "rodrigo.hal@ctf.com"        
              git config --global user.name "Rodrigo HAL"
              git add ${{ env.POSTMAN_FILE }}
              git commit -m 'update postmat schema verion ${{github.event.client_payload.API_VERSION}} via action'

        - name: Push changes
          run: git push 
